[domain]
dimension = 2
polynomial-order = 4

[domain.mesh]
filename = "__SALVUS_FLOW_SPECIAL_TEMP__"
format = "hdf5"

[domain.model]
filename = "__SALVUS_FLOW_SPECIAL_TEMP__"
format = "hdf5"

[domain.geometry]
filename = "__SALVUS_FLOW_SPECIAL_TEMP__"
format = "hdf5"

[output.meta-data]
meta-json-filename = "info.json"

[output.point-data]
filename = "receivers.h5"
format = "asdf"
sampling-interval-in-time-steps = 1
[[output.point-data.receiver]]
location = [ 1010.0, 800.0,]
network-code = "XX"
station-code = "000"
location-code = ""
fields = [ "displacement",]

[[output.point-data.receiver]]
location = [ 1110.0, 800.0,]
network-code = "XX"
station-code = "001"
location-code = ""
fields = [ "displacement",]

[[output.point-data.receiver]]
location = [ 1210.0, 800.0,]
network-code = "XX"
station-code = "002"
location-code = ""
fields = [ "displacement",]

[[output.point-data.receiver]]
location = [ 1310.0, 800.0,]
network-code = "XX"
station-code = "003"
location-code = ""
fields = [ "displacement",]

[[output.point-data.receiver]]
location = [ 1410.0, 800.0,]
network-code = "XX"
station-code = "004"
location-code = ""
fields = [ "displacement",]

[physics.wave-equation]
time-stepping-scheme = "newmark"
start-time-in-seconds = -0.08
end-time-in-seconds = 0.52
time-step-in-seconds = 0.001
attenuation = false
[[physics.wave-equation.point-source]]
location = [ 1000.0, 500.0,]
spatial-type = "vector"
spatial-weights = [ 0.0, -10000000000.0,]

[physics.wave-equation.point-source.source-time-function]
center-frequency = 14.5
wavelet = "ricker"
[[physics.wave-equation.boundaries]]
side-sets = [ "x0", "x1", "y0",]
taper-amplitude = 0.0
type = "absorbing"
width-in-meters = 0.0

