IF("${CMAKE_Fortran_COMPILER_ID}" STREQUAL "GNU")
message("heho")
message(${CMAKE_Fortran_COMPILER_ID})
  SET(CMAKE_Fortran_FLAGS_INIT " -O3 -fopenmp -fdefault-real-8 -fdefault-double-8")
  SET(CMAKE_Fortran_FLAGS_DEBUG_INIT  "-O0 -fno-f2c -fbounds-check -fbacktrace -pg -g  -fopenmp -fdefault-real-8 -fdefault-double-8 -Wall")
  SET(CMAKE_Fortran_FLAGS_RELWITHDEBINFO_INIT "-fbounds-check -fbacktrace -funroll-all-loops -fno-f2c -pg -g  -fopenmp -fdefault-real-8 -fdefault-double-8 -Wall")
  SET(CMAKE_Fortran_FLAGS_RELEASE_INIT "-O3 -funroll-all-loops -fno-f2c -fopenmp -fdefault-real-8 -fdefault-double-8") 
set(Fortran_COMPILER_NAME,"gfortran")
set(CMAKE_Fortran_COMPILER,gfortran)
message(${CMAKE_Fortran_FLAGS_INIT})
message(${CMAKE_Fortran_FLAGS_DEBUG_INIT})
message(${CMAKE_Fortran_FLAGS_RELWITHDEBINFO_INIT})
message(${CMAKE_Fortran_FLAGS_RELEASE_INIT})

ENDIF("${CMAKE_Fortran_COMPILER_ID}" STREQUAL "GNU")
IF("${CMAKE_Fortran_COMPILER_ID}" STREQUAL "Intel")
  SET(CMAKE_Fortran_FLAGS_INIT "-O3 -openmp")
  SET(CMAKE_Fortran_FLAGS_DEBUG_INIT  "-check bounds -backtrace -pg -g -O0")
  SET(CMAKE_Fortran_FLAGS_RELWITHDEBINFO_INIT "-openmp -check bounds -backtrace -pg -g")
  SET(CMAKE_Fortran_FLAGS_RELEASE_INIT "-openmp -O3")
  SET(CMAKE_SHARED_LIBRARY_LINK_Fortran_FLAGS "-static-intel")
ENDIF("${CMAKE_Fortran_COMPILER_ID}" STREQUAL "Intel")

